In [11]:
import pandas as pd
import numpy as np
import math

In [7]:
data = pd.read_csv('withoutnil.csv')

In [8]:
print(data)

        Unnamed: 0 ESTU_TIPODOCUMENTO ESTU_NACIONALIDAD ESTU_GENERO  \
0                0                 TI             SUIZA           F   
1                1                PEP         VENEZUELA           M   
2                2                 TI         VENEZUELA           F   
3                3                 CE         VENEZUELA           M   
4                4                 TI          COLOMBIA           F   
...            ...                ...               ...         ...   
504867      504867                 TI          COLOMBIA           M   
504868      504868                 CC          COLOMBIA           M   
504869      504869                 TI          COLOMBIA           F   
504870      504870                 TI          COLOMBIA           M   
504871      504871                 TI          COLOMBIA           F   

          ESTU_FECHANACIMIENTO  PERIODO  ESTU_CONSECUTIVO ESTU_ESTUDIANTE  \
0       03/03/2003 12:00:00 AM    20204  SB11202040211436      ESTUDIA

In [9]:
null_columns=data.columns[data.isnull().any()]
print(null_columns)

Index([], dtype='object')


In [72]:
def simMatrix(x):
  sim = np.zeros([len(x),len(x)],dtype=np.uint32)
  for i in range( len(x)-1):
    for j in range(i+1,len(x)):
      n = np.nonzero((x[i] == x[j]) == True)
      sim[i][j] = len(n[0])
  return sim/len(x[0])

def ent(sim):
  entro = 0
  for i in range( len(sim)-1):
    for j in range(i+1,len(sim)):
      if sim[i][j] != 0:
        entro += sim[i][j] * math.log(sim[i][j]) + (1 - sim[i][j]) * math.log(sim[i][j])
  return -entro

In [241]:
features = np.arange(1,60)
sub_data = np.array(data[200000:201000])
print(simMatrix(sub_data[:,features]))

[[0.         0.77966102 0.79661017 ... 0.3220339  0.38983051 0.38983051]
 [0.         0.         0.77966102 ... 0.3559322  0.3220339  0.44067797]
 [0.         0.         0.         ... 0.30508475 0.28813559 0.3559322 ]
 ...
 [0.         0.         0.         ... 0.         0.55932203 0.66101695]
 [0.         0.         0.         ... 0.         0.         0.55932203]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [242]:
total = ent(simMatrix(sub_data[:,features]))
print(total)

478669.15646013984


In [243]:
list = []
for i in range(len(features)):
    new = np.array(np.append(features[:i],features[i+1:]))
    list.append((features[i], total - ent(simMatrix(sub_data[:,new]))))
#    print(new)

In [244]:
print(list)


[(1, -8456.667550367827), (2, -14364.845082507469), (3, -2692.411954826268), (4, 8520.166484760004), (5, -14364.845082507469), (6, 8538.66946398199), (7, -14364.845082507469), (8, -14364.845082507469), (9, -9904.770200206607), (10, 7493.75776281039), (11, 7493.75776281039), (12, 8312.454132954997), (13, 8312.454132954997), (14, 2009.1972885039868), (15, 669.1315958055784), (16, 1824.2784291250282), (17, 5367.1928328781505), (18, 5070.731468148646), (19, 5934.760536852875), (20, 3172.2663197399233), (21, -3281.011013716925), (22, -4539.770540673868), (23, -2684.0234818144236), (24, -5413.43494419253), (25, -2960.661160447693), (26, -5547.904705016175), (27, -2697.3583860827493), (28, -7687.622611505911), (29, 1063.4257279979647), (30, 2107.1867383299978), (31, 1652.1169879378867), (32, 1893.0720591846039), (33, -1436.8480497261626), (34, 2304.7119595062686), (35, 3355.7401172494283), (36, -503.12543935049325), (37, -2950.494395520771), (38, 8478.983106065076), (39, 8463.197457634844), (

In [245]:
dtype = [('feaure',int),('value',float)]

a = np.array(list,dtype=dtype)
a = np.sort(a, order='value')
print(a)

[( 2, -14364.84508251) ( 5, -14364.84508251) ( 7, -14364.84508251)
 ( 8, -14364.84508251) (55, -14364.84508251) (43, -14223.4279821 )
 (44, -13441.32627004) (41, -12674.98912476) (48, -12005.97450469)
 ( 9,  -9904.77020021) ( 1,  -8456.66755037) (28,  -7687.62261151)
 (49,  -7491.08966794) (42,  -7346.73949663) (26,  -5547.90470502)
 (24,  -5413.43494419) (22,  -4539.77054067) (21,  -3281.01101372)
 (25,  -2960.66116045) (37,  -2950.49439552) (27,  -2697.35838608)
 ( 3,  -2692.41195483) (23,  -2684.02348181) (33,  -1436.84804973)
 (36,   -503.12543935) (45,   -449.15780291) (15,    669.13159581)
 (29,   1063.425728  ) (31,   1652.11698794) (16,   1824.27842913)
 (32,   1893.07205918) (14,   2009.1972885 ) (30,   2107.18673833)
 (34,   2304.71195951) (50,   2366.22093064) (20,   3172.26631974)
 (35,   3355.74011725) (18,   5070.73146815) (17,   5367.19283288)
 (19,   5934.76053685) (53,   7489.99813545) (54,   7489.99813545)
 (10,   7493.75776281) (11,   7493.75776281) (58,   7499.56661

In [246]:
feature_names = np.array(data.columns)

for i in a:
    print(feature_names[i[0]])


ESTU_NACIONALIDAD
PERIODO
ESTU_ESTUDIANTE
ESTU_PAIS_RESIDE
ESTU_PRIVADO_LIBERTAD
COLE_CALENDARIO
COLE_BILINGUE
COLE_GENERO
COLE_SEDE_PRINCIPAL
ESTU_TIENEETNIA
ESTU_TIPODOCUMENTO
FAMI_TIENECONSOLAVIDEOJUEGOS
COLE_AREA_UBICACION
COLE_NATURALEZA
FAMI_TIENEAUTOMOVIL
FAMI_TIENELAVADORA
FAMI_TIENESERVICIOTV
FAMI_TIENEINTERNET
FAMI_TIENEHORNOMICROOGAS
ESTU_TIPOREMUNERACION
FAMI_TIENEMOTOCICLETA
ESTU_GENERO
FAMI_TIENECOMPUTADOR
FAMI_SITUACIONECONOMICA
ESTU_HORASSEMANATRABAJA
COLE_CARACTER
FAMI_PERSONASHOGAR
FAMI_NUMLIBROS
FAMI_COMECARNEPESCADOHUEVO
FAMI_CUARTOSHOGAR
FAMI_COMECEREALFRUTOSLEGUMBRE
FAMI_ESTRATOVIVIENDA
FAMI_COMELECHEDERIVADOS
ESTU_DEDICACIONLECTURADIARIA
COLE_JORNADA
FAMI_TRABAJOLABORMADRE
ESTU_DEDICACIONINTERNET
FAMI_EDUCACIONMADRE
FAMI_EDUCACIONPADRE
FAMI_TRABAJOLABORPADRE
COLE_COD_DEPTO_UBICACION
COLE_DEPTO_UBICACION
ESTU_DEPTO_RESIDE
ESTU_COD_RESIDE_DEPTO
ESTU_DEPTO_PRESENTACION
ESTU_COD_DEPTO_PRESENTACION
ESTU_COD_MCPIO_PRESENTACION
ESTU_MCPIO_PRESENTACION
COLE_COD_MCPIO_UBI

Se ve claramente que el valor de periodo y de estu_estudiante son los menos significativos, por lo que se eliminan de la lista de features y se procede a realizar más iteraciones

In [247]:
features = np.array(np.append(features[:4],features[4+1:]))
features = np.array(np.append(features[:5],features[5+1:]))
print(features)

[ 1  2  3  4  6  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
 51 52 53 54 55 56 57 58 59]


In [248]:
total = ent(simMatrix(sub_data[:,features]))
list = []
for i in range(len(features)):
    new = np.array(np.append(features[:i],features[i+1:]))
    list.append((features[i], total - ent(simMatrix(sub_data[:,new]))))

a = np.array(list,dtype=dtype)
a = np.sort(a, order='value')

print(a)

for i in a:
    print(feature_names[i[0]])


[( 2, -16455.65632409) ( 8, -16455.65632409) (55, -16455.65632409)
 (43, -16298.98597961) (44, -15426.46762278) (41, -14584.42935689)
 (48, -13838.00777785) ( 9, -11497.65354453) ( 1,  -9898.62761712)
 (28,  -9033.11015225) (49,  -8829.85739624) (42,  -8664.95425184)
 (26,  -6662.44850685) (24,  -6510.80084094) (22,  -5548.962797  )
 (21,  -4141.26111307) (25,  -3805.28548493) (37,  -3790.82334779)
 (27,  -3533.18984347) ( 3,  -3527.28612068) (23,  -3489.52245089)
 (33,  -2135.05420301) (36,  -1092.91682816) (45,  -1048.06177439)
 (15,    188.1314676 ) (29,    620.41258781) (31,   1276.04085356)
 (16,   1462.78749094) (32,   1535.52847219) (14,   1670.45539669)
 (30,   1779.06009784) (34,   1984.43228543) (50,   2059.17484843)
 (20,   2948.61523864) (35,   3151.25123699) (18,   5040.21353042)
 (17,   5364.22519699) (19,   5985.76075153) (53,   7714.09481339)
 (54,   7714.09481339) (10,   7718.32495388) (11,   7718.32495388)
 (58,   7724.23768456) (59,   7724.23768456) (56,   8558.66094

Ahora retirar Estu_privado_de_la_libertad

In [249]:
for i in range(len(features)-1):
    if features[i] == a[0][0]:
        features = np.delete(features,[i])
print(features)

[ 1  3  4  6  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51
 52 53 54 55 56 57 58 59]


In [250]:
def delf(features):
    total = ent(simMatrix(sub_data[:,features]))
    list = []
    for i in range(len(features)):
        new = np.array(np.append(features[:i],features[i+1:]))
        list.append((features[i], total - ent(simMatrix(sub_data[:,new]))))

    a = np.array(list,dtype=dtype)
    a = np.sort(a, order='value')

#    for i in a:
#        print(feature_names[i[0]])

    print("******** Deleting ",feature_names[a[0][0]])
    for i in range(len(features)-1):
        if features[i] == a[0][0]:
            return np.delete(features,[i])

In [251]:
features = delf(features)
print(features)

******** Deleting  ESTU_PAIS_RESIDE
[ 1  3  4  6  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59]


Ahora se elemina Cole_calendario
A partir de aquí se implemente in ciclo para agilizar el proceso y empezaremos por sacar otras 10 carácterísticas, desde ahí se decidirá si es prudente sacar más o no

In [252]:
for i in range(15):
    features = delf(features)



******** Deleting  ESTU_PRIVADO_LIBERTAD
******** Deleting  COLE_CALENDARIO
******** Deleting  COLE_BILINGUE
******** Deleting  COLE_GENERO
******** Deleting  COLE_SEDE_PRINCIPAL
******** Deleting  ESTU_TIENEETNIA
******** Deleting  ESTU_TIPODOCUMENTO
******** Deleting  COLE_AREA_UBICACION
******** Deleting  FAMI_TIENECONSOLAVIDEOJUEGOS
******** Deleting  COLE_NATURALEZA
******** Deleting  FAMI_TIENEAUTOMOVIL
******** Deleting  FAMI_TIENELAVADORA
******** Deleting  FAMI_TIENESERVICIOTV
******** Deleting  FAMI_TIENEINTERNET
******** Deleting  FAMI_TIENEHORNOMICROOGAS


In [253]:
for i in features:
    print(feature_names[i])

ESTU_GENERO
ESTU_FECHANACIMIENTO
ESTU_CONSECUTIVO
ESTU_DEPTO_RESIDE
ESTU_COD_RESIDE_DEPTO
ESTU_MCPIO_RESIDE
ESTU_COD_RESIDE_MCPIO
FAMI_ESTRATOVIVIENDA
FAMI_PERSONASHOGAR
FAMI_CUARTOSHOGAR
FAMI_EDUCACIONPADRE
FAMI_EDUCACIONMADRE
FAMI_TRABAJOLABORPADRE
FAMI_TRABAJOLABORMADRE
FAMI_TIENECOMPUTADOR
FAMI_TIENEMOTOCICLETA
FAMI_NUMLIBROS
FAMI_COMELECHEDERIVADOS
FAMI_COMECARNEPESCADOHUEVO
FAMI_COMECEREALFRUTOSLEGUMBRE
FAMI_SITUACIONECONOMICA
ESTU_DEDICACIONLECTURADIARIA
ESTU_DEDICACIONINTERNET
ESTU_HORASSEMANATRABAJA
ESTU_TIPOREMUNERACION
COLE_CODIGO_ICFES
COLE_COD_DANE_ESTABLECIMIENTO
COLE_NOMBRE_ESTABLECIMIENTO
COLE_CARACTER
COLE_COD_DANE_SEDE
COLE_NOMBRE_SEDE
COLE_JORNADA
COLE_COD_MCPIO_UBICACION
COLE_MCPIO_UBICACION
COLE_COD_DEPTO_UBICACION
COLE_DEPTO_UBICACION
ESTU_COD_MCPIO_PRESENTACION
ESTU_MCPIO_PRESENTACION
ESTU_DEPTO_PRESENTACION
ESTU_COD_DEPTO_PRESENTACION


In [254]:
for i in range(5):
    features = delf(features)

******** Deleting  FAMI_TIENEMOTOCICLETA
******** Deleting  FAMI_TIENECOMPUTADOR
******** Deleting  ESTU_TIPOREMUNERACION
******** Deleting  ESTU_GENERO
******** Deleting  FAMI_SITUACIONECONOMICA


In [255]:
for i in features:
    print(feature_names[i])


ESTU_FECHANACIMIENTO
ESTU_CONSECUTIVO
ESTU_DEPTO_RESIDE
ESTU_COD_RESIDE_DEPTO
ESTU_MCPIO_RESIDE
ESTU_COD_RESIDE_MCPIO
FAMI_ESTRATOVIVIENDA
FAMI_PERSONASHOGAR
FAMI_CUARTOSHOGAR
FAMI_EDUCACIONPADRE
FAMI_EDUCACIONMADRE
FAMI_TRABAJOLABORPADRE
FAMI_TRABAJOLABORMADRE
FAMI_NUMLIBROS
FAMI_COMELECHEDERIVADOS
FAMI_COMECARNEPESCADOHUEVO
FAMI_COMECEREALFRUTOSLEGUMBRE
ESTU_DEDICACIONLECTURADIARIA
ESTU_DEDICACIONINTERNET
ESTU_HORASSEMANATRABAJA
COLE_CODIGO_ICFES
COLE_COD_DANE_ESTABLECIMIENTO
COLE_NOMBRE_ESTABLECIMIENTO
COLE_CARACTER
COLE_COD_DANE_SEDE
COLE_NOMBRE_SEDE
COLE_JORNADA
COLE_COD_MCPIO_UBICACION
COLE_MCPIO_UBICACION
COLE_COD_DEPTO_UBICACION
COLE_DEPTO_UBICACION
ESTU_COD_MCPIO_PRESENTACION
ESTU_MCPIO_PRESENTACION
ESTU_DEPTO_PRESENTACION
ESTU_COD_DEPTO_PRESENTACION
